### PR TITLE
Updating UI and behavior after registering 

### PR DESCRIPTION
**Pull request by jtkabenni**
## Description

Updates to behavior and UI after user registration:
- redirected to home page after account created
- Welcome message modal appears after user authenticates for the first time (creating account)
- Modal does not appear again after it is closed out 
- user context created so logged in user information is global
- firebase API functions for user added to new api file
- new field closedConfirmationMessage added to DB to track whether user has closed message or not 

## Related Issue

https://cherryontech-jupiter-jumpers.atlassian.net/browse/SCRUM-12
https://cherryontech-jupiter-jumpers.atlassian.net/browse/SCRUM-13

## Related Story Card

_Provide a link to the relevant story card._

## Type of Changes

Feature update.

## Acceptance Criteria

- [x] User is taken to home page after creating account 
- [x] The confirmation modal appears after creating account 
- [x] The user can click 'get started' to close out the modal
- [x] After refreshing, the user remains logged in
- [x] The confirmation modal does not appear again after it is closed 

### Before
This was the view pre and post authentication 
Screenshot 2024-04-27 at 5 22 44 PM

### After

Modal appears after first authentication
Screenshot 2024-04-27 at 5 13 38 PM

UI reflects logged in state
Screenshot 2024-04-27 at 5 13 46 PM

## Testing Instructions

1. Create an account
2. Make sure app directs you to home page (/)
3. View confirmation message modal
4. Close out modal
5. Make sure app reflects logged in state
6. Refresh to make sure you remain logged in (this takes a second so the logged out state will flash initially)

## Learnings (Optional)

_Document any things you learned or 'gotchas' you experienced._

### CODE REVIEW

**Comment by jtkabenni** [comment]
To do: 
- styling to match design, but wanted to see if storybook UI would impact this? 
- wrote some files in js and need to convert to ts

**Review by paola4 — APPROVED** [review]
I went through all the testing and acceptance criteria and it all checks out. The only thing I think we need to come back to later is that, when you refresh as a logged in user, the logged out state flashes for long enough that a user could interpret it as an error. It _does_ keep the user logged in, though; it's just a brief flash (which Jenny points out in the PR notes).

**Comment by paola4** [comment]
> To do:
> 
>     * styling to match design, but wanted to see if storybook UI would impact this?
> 
>     * wrote some files in js and need to convert to ts

I can add the components to Storybook, with updated styling to match the new wireframe!

**Review by GinaCastromonte — APPROVED** [review]
Looks great! The functionality worked according to the Jira needs.  I did notice as well the state management is a little buggy when page is refreshed.  I will take the task of fixing our auth/state management so that we can move on to the next sprint.

**Pull request merged**
